# Generated by Django 5.2.4 on 2025-08-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rapportproduction",
            name="poids_assemblage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Poids assemblage total",
            ),
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="poids_debitage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Poids débitage total",
            ),
        ),
    ]
