# Generated by Django 5.2.4 on 2025-09-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_rapportproduction_poids_assemblage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rapportproduction",
            name="poids_assemblage",
        ),
        migrations.RemoveField(
            model_name="rapportproduction",
            name="poids_debitage",
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="nb_lancements_assemblage",
            field=models.IntegerField(
                default=0, verbose_name="Nombre de lancements assemblage"
            ),
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="nb_lancements_debitage",
            field=models.IntegerField(
                default=0, verbose_name="Nombre de lancements débitage"
            ),
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="poids_assemblage_total",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Poids assemblage total",
            ),
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="poids_debitage_1_total",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Poids débitage 1 total",
            ),
        ),
        migrations.AddField(
            model_name="rapportproduction",
            name="poids_debitage_2_total",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Poids débitage 2 total",
            ),
        ),
        migrations.AlterField(
            model_name="rapportproduction",
            name="poids_total",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                verbose_name="Poids total traité",
            ),
        ),
        migrations.AddIndex(
            model_name="rapportproduction",
            index=models.Index(
                fields=["date_debut", "date_fin"], name="rapport_pro_date_de_6d6baf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rapportproduction",
            index=models.Index(
                fields=["type_rapport"], name="rapport_pro_type_ra_813f4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rapportproduction",
            index=models.Index(
                fields=["created_at"], name="rapport_pro_created_ff2168_idx"
            ),
        ),
    ]
