# Generated by Django 5.2.4 on 2025-07-19 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaborateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Affaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_affaire",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code affaire"
                    ),
                ),
                ("livrable", models.TextField(verbose_name="Description du livrable")),
                (
                    "client",
                    models.CharField(max_length=100, verbose_name="Nom du client"),
                ),
                ("date_debut", models.DateField(verbose_name="Date de début")),
                (
                    "date_fin_prevue",
                    models.DateField(verbose_name="Date de fin prévue"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("suspendue", "Suspendue"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_cours",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "responsable_affaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affaires_responsable",
                        to="collaborateurs.collaborateur",
                        verbose_name="Responsable de l'affaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affaire",
                "verbose_name_plural": "Affaires",
                "db_table": "affaire",
                "ordering": ["-date_debut"],
            },
        ),
    ]
