# Generated by Django 5.2.4 on 2025-07-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la permission"
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("collaborateurs", "Collaborateurs"),
                            ("ateliers", "Ateliers"),
                            ("categories", "Catégories"),
                            ("affaires", "Affaires"),
                            ("lancements", "Lancements"),
                            ("rapports", "Rapports"),
                            ("administration", "Administration"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Créer"),
                            ("read", "Lire"),
                            ("update", "Modifier"),
                            ("delete", "Supprimer"),
                            ("assign", "Assigner"),
                            ("export", "Exporter"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "unique_together": {("module", "action")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom du rôle"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="Rôle système"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="core.permission", verbose_name="Permissions"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle",
                "verbose_name_plural": "Rôles",
            },
        ),
    ]
