# Generated by Django 5.2.4 on 2025-08-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_permission_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="code_affaire",
            field=models.CharField(max_length=50, verbose_name="Code affaire"),
        ),
    ]
