# Generated by Django 5.2.4 on 2025-08-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_affaire_code_affaire"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="affaire",
            options={
                "ordering": ["-date_debut", "-created_at"],
                "verbose_name": "Affaire",
                "verbose_name_plural": "Affaires",
            },
        ),
        migrations.AlterField(
            model_name="affaire",
            name="client",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du client"
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="code_affaire",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Code affaire"
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="date_debut",
            field=models.DateField(blank=True, null=True, verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="date_fin_prevue",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de fin prévue"
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="livrable",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description du livrable"
            ),
        ),
        migrations.AlterField(
            model_name="affaire",
            name="statut",
            field=models.CharField(
                choices=[("en_cours", "En cours"), ("terminee", "Terminée")],
                default="en_cours",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
    ]
