# Generated by Django 5.2.4 on 2025-08-19 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0005_fix_constraints_final"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="affaire",
            name="livrable",
            field=models.TextField(
                blank=True, null=True, verbose_name="Nom du livrable"
            ),
        ),
        migrations.CreateModel(
            name="PreferenceNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notifications_lancements",
                    models.BooleanField(
                        default=True, verbose_name="Notifications lancements"
                    ),
                ),
                (
                    "notifications_affaires",
                    models.BooleanField(
                        default=True, verbose_name="Notifications affaires"
                    ),
                ),
                (
                    "notifications_systeme",
                    models.BooleanField(
                        default=True, verbose_name="Notifications système"
                    ),
                ),
                (
                    "notifications_email",
                    models.BooleanField(
                        default=False, verbose_name="Notifications par email"
                    ),
                ),
                (
                    "frequence_resume",
                    models.CharField(
                        choices=[
                            ("immediate", "Immédiate"),
                            ("hourly", "Toutes les heures"),
                            ("daily", "Quotidienne"),
                            ("weekly", "Hebdomadaire"),
                            ("none", "Aucune"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Fréquence du résumé",
                    ),
                ),
                (
                    "heure_debut_silencieux",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Début période silencieuse"
                    ),
                ),
                (
                    "heure_fin_silencieux",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Fin période silencieuse"
                    ),
                ),
                (
                    "utilisateur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
                "db_table": "preference_notification",
            },
        ),
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("assign", "Assignation"),
                            ("status_change", "Changement de statut"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("collaborateurs", "Collaborateurs"),
                            ("ateliers", "Ateliers"),
                            ("categories", "Catégories"),
                            ("affaires", "Affaires"),
                            ("lancements", "Lancements"),
                            ("rapports", "Rapports"),
                            ("administration", "Administration"),
                            ("system", "Système"),
                        ],
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "adresse_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "donnees_avant",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données avant"
                    ),
                ),
                (
                    "donnees_après",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données après"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité",
                "verbose_name_plural": "Activités",
                "db_table": "activite",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["date_creation"], name="activite_date_cr_070726_idx"
                    ),
                    models.Index(
                        fields=["utilisateur", "date_creation"],
                        name="activite_utilisa_43886d_idx",
                    ),
                    models.Index(
                        fields=["module", "action"], name="activite_module_4c279f_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="activite_content_90ca99_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Succès"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("system", "Système"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                ("message", models.TextField(verbose_name="Message")),
                ("lu", models.BooleanField(default=False, verbose_name="Lu")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de lecture"
                    ),
                ),
                (
                    "url_action",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="URL d'action",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notification",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["destinataire", "lu"],
                        name="notificatio_destina_afcb9c_idx",
                    ),
                    models.Index(
                        fields=["date_creation"], name="notificatio_date_cr_149469_idx"
                    ),
                    models.Index(
                        fields=["type_notification"],
                        name="notificatio_type_no_99f075_idx",
                    ),
                ],
            },
        ),
    ]
