# Generated by Django 5.2.4 on 2025-08-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ateliers", "0004_remove_atelier_capacite_max"),
        ("core", "0006_alter_affaire_livrable_preferencenotification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffaireCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "affaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affaire_categories",
                        to="core.affaire",
                        verbose_name="Affaire",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affaire_categories",
                        to="ateliers.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Association Affaire-Catégorie",
                "verbose_name_plural": "Associations Affaire-Catégorie",
                "db_table": "affaire_categorie",
                "ordering": ["affaire__code_affaire", "categorie__nom_categorie"],
                "unique_together": {("affaire", "categorie")},
            },
        ),
    ]
