# Generated by Django 5.2.4 on 2025-07-19 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaborateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_categorie",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la catégorie"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
                "db_table": "categorie",
                "ordering": ["nom_categorie"],
            },
        ),
        migrations.CreateModel(
            name="Atelier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_atelier",
                    models.CharField(max_length=100, verbose_name="Nom de l'atelier"),
                ),
                (
                    "type_atelier",
                    models.CharField(
                        choices=[
                            ("fabrication", "Fabrication"),
                            ("assemblage", "Assemblage"),
                            ("finition", "Finition"),
                            ("controle", "Contrôle qualité"),
                        ],
                        max_length=50,
                        verbose_name="Type d'atelier",
                    ),
                ),
                (
                    "capacite_max",
                    models.IntegerField(default=0, verbose_name="Capacité maximale"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "responsable_atelier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ateliers_responsable",
                        to="collaborateurs.collaborateur",
                        verbose_name="Responsable de l'atelier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atelier",
                "verbose_name_plural": "Ateliers",
                "db_table": "atelier",
                "ordering": ["nom_atelier"],
            },
        ),
        migrations.CreateModel(
            name="AtelierCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacite_categorie",
                    models.IntegerField(
                        default=0, verbose_name="Capacité pour cette catégorie"
                    ),
                ),
                (
                    "temps_moyen_traitement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Temps moyen de traitement (heures)",
                    ),
                ),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ateliers.atelier",
                        verbose_name="Atelier",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ateliers.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capacité Atelier-Catégorie",
                "verbose_name_plural": "Capacités Atelier-Catégorie",
                "db_table": "atelier_categorie",
                "unique_together": {("atelier", "categorie")},
            },
        ),
        migrations.CreateModel(
            name="CollaborateurAtelier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_affectation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date d'affectation"
                    ),
                ),
                (
                    "date_fin_affectation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin d'affectation"
                    ),
                ),
                (
                    "role_dans_atelier",
                    models.CharField(
                        choices=[
                            ("operateur", "Opérateur"),
                            ("chef_equipe", "Chef d'équipe"),
                            ("technicien", "Technicien"),
                            ("controleur", "Contrôleur"),
                        ],
                        max_length=50,
                        verbose_name="Rôle dans l'atelier",
                    ),
                ),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ateliers.atelier",
                        verbose_name="Atelier",
                    ),
                ),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborateurs.collaborateur",
                        verbose_name="Collaborateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation Collaborateur-Atelier",
                "verbose_name_plural": "Affectations Collaborateur-Atelier",
                "db_table": "collaborateur_atelier",
                "unique_together": {("collaborateur", "atelier")},
            },
        ),
        migrations.CreateModel(
            name="CollaborateurCategorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "niveau_competence",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                            ("expert", "Expert"),
                        ],
                        max_length=20,
                        verbose_name="Niveau de compétence",
                    ),
                ),
                (
                    "date_certification",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de certification"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ateliers.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborateurs.collaborateur",
                        verbose_name="Collaborateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spécialisation Collaborateur-Catégorie",
                "verbose_name_plural": "Spécialisations Collaborateur-Catégorie",
                "db_table": "collaborateur_categorie",
                "unique_together": {("collaborateur", "categorie")},
            },
        ),
    ]
