# Generated by Django 5.2.4 on 2025-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ateliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atelier",
            name="type_atelier",
            field=models.CharField(
                choices=[
                    ("fabrication", "Fabrication"),
                    ("assemblage", "Assemblage"),
                    ("finition", "Finition"),
                    ("controle", "Contrôle qualité"),
                    ("debitage", "Débitage"),
                ],
                max_length=50,
                verbose_name="Type d'atelier",
            ),
        ),
    ]
