# Generated by Django 5.2.4 on 2025-08-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ateliers", "0002_alter_atelier_type_atelier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ateliercategorie",
            options={
                "verbose_name": "Relation Atelier-Catégorie",
                "verbose_name_plural": "Relations Atelier-Catégorie",
            },
        ),
        migrations.RemoveField(
            model_name="ateliercategorie",
            name="capacite_categorie",
        ),
        migrations.RemoveField(
            model_name="ateliercategorie",
            name="temps_moyen_traitement",
        ),
        migrations.RemoveField(
            model_name="collaborateuratelier",
            name="date_affectation",
        ),
        migrations.RemoveField(
            model_name="collaborateuratelier",
            name="date_fin_affectation",
        ),
        migrations.RemoveField(
            model_name="collaborateuratelier",
            name="role_dans_atelier",
        ),
        migrations.RemoveField(
            model_name="collaborateurcategorie",
            name="date_certification",
        ),
        migrations.RemoveField(
            model_name="collaborateurcategorie",
            name="niveau_competence",
        ),
    ]
