# Generated by Django 5.2.4 on 2025-08-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ateliers", "0003_alter_ateliercategorie_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atelier",
            name="capacite_max",
        ),
    ]
