# Generated by Django 5.2.4 on 2025-07-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collaborateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_collaborateur",
                    models.CharField(max_length=100, verbose_name="Nom"),
                ),
                (
                    "prenom_collaborateur",
                    models.CharField(max_length=100, verbose_name="Prénom"),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Mot de passe"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrateur"),
                            ("manager", "Manager"),
                            ("employee", "Employé"),
                        ],
                        max_length=50,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collaborateur",
                "verbose_name_plural": "Collaborateurs",
                "db_table": "collaborateur",
                "ordering": ["nom_collaborateur", "prenom_collaborateur"],
            },
        ),
    ]
