# Generated by Django 5.2.4 on 2025-07-27 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborateurs", "0001_initial"),
        ("core", "0002_permission_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="user_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.role",
                verbose_name="Rôle utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="collaborateur",
            name="role",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="RoleHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_reason",
                    models.TextField(blank=True, verbose_name="Raison du changement"),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_made",
                        to="collaborateurs.collaborateur",
                    ),
                ),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collaborateurs.collaborateur",
                    ),
                ),
                (
                    "new_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_assignments",
                        to="core.role",
                    ),
                ),
                (
                    "old_role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_assignments",
                        to="core.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique des rôles",
                "verbose_name_plural": "Historique des rôles",
            },
        ),
    ]
