# Generated by Django 5.2.4 on 2025-07-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collaborateurs",
            "0002_collaborateur_user_role_alter_collaborateur_role_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborateur",
            name="role",
        ),
        migrations.AddField(
            model_name="collaborateur",
            name="email",
            field=models.EmailField(
                blank=True,
                default=None,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="Email",
            ),
        ),
    ]
