# Generated by Django 5.2.4 on 2025-07-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborateurs", "0003_remove_collaborateur_role_collaborateur_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaborateur",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="collaborateur",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="collaborateur",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="collaborateur",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
