# Generated by Django 5.2.4 on 2025-07-19 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ateliers", "0001_initial"),
        ("collaborateurs", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "num_lanc",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de lancement"
                    ),
                ),
                ("date_reception", models.DateField(verbose_name="Date de réception")),
                ("date_lancement", models.DateField(verbose_name="Date de lancement")),
                (
                    "sous_livrable",
                    models.TextField(verbose_name="Description du sous-livrable"),
                ),
                (
                    "poids_debitage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Poids débitage (kg)",
                    ),
                ),
                (
                    "poids_assemblage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Poids assemblage (kg)",
                    ),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observations"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("en_attente", "En attente"),
                        ],
                        default="planifie",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "affaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancements",
                        to="core.affaire",
                        verbose_name="Affaire",
                    ),
                ),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancements",
                        to="ateliers.atelier",
                        verbose_name="Atelier",
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancements",
                        to="ateliers.categorie",
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "collaborateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lancements",
                        to="collaborateurs.collaborateur",
                        verbose_name="Collaborateur responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lancement",
                "verbose_name_plural": "Lancements",
                "db_table": "lancement",
                "ordering": ["-date_lancement"],
            },
        ),
    ]
