# Generated by Django 5.2.4 on 2025-08-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancement",
            name="num_lanc",
            field=models.CharField(max_length=50, verbose_name="Numéro de lancement"),
        ),
    ]
