# Generated by Django 5.2.4 on 2025-08-14 00:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ateliers", "0003_alter_ateliercategorie_options_and_more"),
        ("core", "0003_alter_affaire_code_affaire"),
        ("lancements", "0002_alter_lancement_num_lanc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lancement",
            options={
                "ordering": ["-date_lancement", "-created_at"],
                "verbose_name": "Lancement",
                "verbose_name_plural": "Lancements",
            },
        ),
        migrations.AddIndex(
            model_name="lancement",
            index=models.Index(
                fields=["date_lancement"], name="lancement_date_la_fc5ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lancement",
            index=models.Index(fields=["statut"], name="lancement_statut_865301_idx"),
        ),
        migrations.AddIndex(
            model_name="lancement",
            index=models.Index(fields=["affaire"], name="lancement_affaire_eebb7a_idx"),
        ),
        migrations.AddIndex(
            model_name="lancement",
            index=models.Index(fields=["atelier"], name="lancement_atelier_37fc53_idx"),
        ),
    ]
