# Generated by Django 5.2.4 on 2025-08-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancements", "0003_alter_lancement_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancement",
            name="poids_assemblage",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Poids assemblage (kg)",
            ),
        ),
        migrations.AlterField(
            model_name="lancement",
            name="poids_debitage",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=10,
                verbose_name="Poids débitage (kg)",
            ),
        ),
    ]
