# Generated by Django 5.2.4 on 2025-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lancements", "0004_alter_lancement_poids_assemblage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lancement",
            name="date_lancement",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de lancement prévue"
            ),
        ),
    ]
