# Generated by Django 5.2.4 on 2025-09-14 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ateliers", "0004_remove_atelier_capacite_max"),
        ("core", "0006_alter_affaire_livrable_preferencenotification_and_more"),
        ("lancements", "0005_alter_lancement_date_lancement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lancement",
            name="poids_debitage",
        ),
        migrations.AddField(
            model_name="lancement",
            name="poids_debitage_1",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Poids débitage 1 (kg)",
            ),
        ),
        migrations.AddField(
            model_name="lancement",
            name="poids_debitage_2",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Poids débitage 2 (kg)",
            ),
        ),
        migrations.AddField(
            model_name="lancement",
            name="type_production",
            field=models.CharField(
                choices=[("assemblage", "Assemblage"), ("debitage", "Débitage")],
                default="assemblage",
                max_length=20,
                verbose_name="Type de production",
            ),
        ),
        migrations.AlterField(
            model_name="lancement",
            name="poids_assemblage",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Poids assemblage (kg)",
            ),
        ),
        migrations.AddIndex(
            model_name="lancement",
            index=models.Index(
                fields=["type_production"], name="lancement_type_pr_df4e80_idx"
            ),
        ),
    ]
